### ISSUE TITLE
Community installations map

### ISSUE THREAD

**Issue by sackmanna** [gdcc/dataverse-action#15]
1. Name: UC Berkeley Library Dataverse 
2. URL: https://datasets.lib.berkeley.edu/
3. lat/long: 37.8721922,-122.2594984
4. Year it started: 2024
5. Short description: All data in the UC Berkeley Library Dataverse has been acquired and licensed by the library for use by UC Berkeley and Lawrence Berkeley National Lab students, faculty, and staff. Data records and terms are viewable by any user, regardless of affiliation. Please login to the repository using a Calnet (or LBNL) ID and passphrase to view and download data files. Note that accessing some data files requires agreeing to the terms of use as listed in the guestbook functionality. Research data (i.e. data, code, and other outputs generated during the research process) are not stored on UC Berkeley Library’s Dataverse. 
6. Email contact: librarydataservices@berkeley.edu
7. DOI authority: EZID

**Comment by pdurbin** [comment]
@sackmanna hi! I'm so excited to welcome UC Berkeley to Dataverse!

One thing, could you please go create the issue over at https://github.com/IQSS/dataverse-installations ? Thanks! ❤️

**Comment by pdurbin** [comment]
Closing in favor of this issue:

- https://github.com/IQSS/dataverse-installations/issues/249

Thanks for creating it, @sackmanna!
